# Generated by Django 5.1 on 2024-09-25 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="middle_gravity",
        ),
        migrations.AddField(
            model_name="batch",
            name="ingredients",
            field=models.ManyToManyField(
                through="main.BatchIngredient", to="main.ingredient"
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="batch_number",
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name="batch",
            name="final_gravity",
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name="batchingredient",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.batch"
            ),
        ),
    ]
