# Generated by Django 5.1 on 2024-09-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_batch_middle_gravity_batch_ingredients_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="batch_number",
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="batch",
            name="final_gravity",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
