# Generated by Django 5.1 on 2024-09-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_batch_batch_number_alter_batch_final_gravity"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="middle_gravity",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
