# Generated by Django 5.1 on 2024-09-29 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_batch_middle_gravity"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="batchingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("LITTER", "ltr"),
                    ("MILLILITER", "ml"),
                    ("KILOGRAM", "kg"),
                    ("GRAMS", "gr"),
                    ("MILlGRAMS", "mlg"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="FinishedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[("WINE", "Wine"), ("MEAD", "Mead")], max_length=4
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("start_date", models.DateField()),
                ("finish_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("abv", models.FloatField(verbose_name="ABV (%)")),
                (
                    "batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finished_product",
                        to="main.batch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bottle_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("volume", models.FloatField(help_text="Volume in liters")),
                (
                    "finished_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bottles",
                        to="main.finishedproduct",
                    ),
                ),
            ],
        ),
    ]
