# Generated by Django 5.1 on 2024-09-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_batch_is_finished_alter_batchingredient_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("oz", "Ounces"),
                    ("lb", "Pounds"),
                    ("g", "Grams"),
                    ("l", "Liters"),
                    ("ml", "Milliliters"),
                ],
                max_length=10,
            ),
        ),
    ]
