# Generated by Django 5.1 on 2024-09-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_batchingredient_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="bottle",
            name="date_bottled",
            field=models.DateField(blank=True, null=True),
        ),
    ]
