# Generated by Django 5.1 on 2024-10-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_batch_creator_finishedproduct_creator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="user",
        ),
    ]
