# Generated by Django 5.1 on 2024-10-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_finishedproduct_creator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sharedproduct",
            name="shared_with",
        ),
    ]
