# Generated by Django 5.1 on 2024-10-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_productlike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "Kilograms"),
                    ("g", "Grams"),
                    ("l", "Liters"),
                    ("ml", "Milliliters"),
                ],
                max_length=10,
            ),
        ),
    ]
